# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='alias',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
