# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_creditcard_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='password',
            new_name='hash_pass',
        ),
    ]
