# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170514_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='hash_pass',
            new_name='password',
        ),
    ]
